export type LibroBiblia = {
  nombre: string;
  abrev: string;
  osis: string;
  capitulos: number;
  testamento: "AT" | "NT";
};

export const LIBROS_BIBLIA: LibroBiblia[] = [
  // ─── Antiguo Testamento ───────────────────────────────────────────────────
  { nombre: "Génesis",                 abrev: "Gn",     osis: "GEN", capitulos: 50,  testamento: "AT" },
  { nombre: "Éxodo",                   abrev: "Ex",     osis: "EXO", capitulos: 40,  testamento: "AT" },
  { nombre: "Levítico",                abrev: "Lv",     osis: "LEV", capitulos: 27,  testamento: "AT" },
  { nombre: "Números",                 abrev: "Nm",     osis: "NUM", capitulos: 36,  testamento: "AT" },
  { nombre: "Deuteronomio",            abrev: "Dt",     osis: "DEU", capitulos: 34,  testamento: "AT" },
  { nombre: "Josué",                   abrev: "Jos",    osis: "JOS", capitulos: 24,  testamento: "AT" },
  { nombre: "Jueces",                  abrev: "Jue",    osis: "JDG", capitulos: 21,  testamento: "AT" },
  { nombre: "Rut",                     abrev: "Rt",     osis: "RUT", capitulos: 4,   testamento: "AT" },
  { nombre: "1 Samuel",                abrev: "1 Sam",  osis: "1SA", capitulos: 31,  testamento: "AT" },
  { nombre: "2 Samuel",                abrev: "2 Sam",  osis: "2SA", capitulos: 24,  testamento: "AT" },
  { nombre: "1 Reyes",                 abrev: "1 Re",   osis: "1KI", capitulos: 22,  testamento: "AT" },
  { nombre: "2 Reyes",                 abrev: "2 Re",   osis: "2KI", capitulos: 25,  testamento: "AT" },
  { nombre: "1 Crónicas",              abrev: "1 Cro",  osis: "1CH", capitulos: 29,  testamento: "AT" },
  { nombre: "2 Crónicas",              abrev: "2 Cro",  osis: "2CH", capitulos: 36,  testamento: "AT" },
  { nombre: "Esdras",                  abrev: "Esd",    osis: "EZR", capitulos: 10,  testamento: "AT" },
  { nombre: "Nehemías",                abrev: "Neh",    osis: "NEH", capitulos: 13,  testamento: "AT" },
  { nombre: "Tobías",                  abrev: "Tb",     osis: "TOB", capitulos: 14,  testamento: "AT" },
  { nombre: "Judit",                   abrev: "Jdt",    osis: "JDT", capitulos: 16,  testamento: "AT" },
  { nombre: "Ester",                   abrev: "Est",    osis: "EST", capitulos: 10,  testamento: "AT" },
  { nombre: "1 Macabeos",              abrev: "1 Mac",  osis: "1MA", capitulos: 16,  testamento: "AT" },
  { nombre: "2 Macabeos",              abrev: "2 Mac",  osis: "2MA", capitulos: 15,  testamento: "AT" },
  { nombre: "Job",                     abrev: "Job",    osis: "JOB", capitulos: 42,  testamento: "AT" },
  { nombre: "Salmos",                  abrev: "Sal",    osis: "PSA", capitulos: 150, testamento: "AT" },
  { nombre: "Proverbios",              abrev: "Prov",   osis: "PRO", capitulos: 31,  testamento: "AT" },
  { nombre: "Eclesiastés",             abrev: "Ecl",    osis: "ECC", capitulos: 12,  testamento: "AT" },
  { nombre: "Cantar de los Cantares",  abrev: "Cant",   osis: "SNG", capitulos: 8,   testamento: "AT" },
  { nombre: "Sabiduría",               abrev: "Sab",    osis: "WIS", capitulos: 19,  testamento: "AT" },
  { nombre: "Sirácida",                abrev: "Sir",    osis: "SIR", capitulos: 51,  testamento: "AT" },
  { nombre: "Isaías",                  abrev: "Is",     osis: "ISA", capitulos: 66,  testamento: "AT" },
  { nombre: "Jeremías",                abrev: "Jr",     osis: "JER", capitulos: 52,  testamento: "AT" },
  { nombre: "Lamentaciones",           abrev: "Lam",    osis: "LAM", capitulos: 5,   testamento: "AT" },
  { nombre: "Baruc",                   abrev: "Bar",    osis: "BAR", capitulos: 6,   testamento: "AT" },
  { nombre: "Ezequiel",                abrev: "Ez",     osis: "EZK", capitulos: 48,  testamento: "AT" },
  { nombre: "Daniel",                  abrev: "Dn",     osis: "DAN", capitulos: 14,  testamento: "AT" },
  { nombre: "Oseas",                   abrev: "Os",     osis: "HOS", capitulos: 14,  testamento: "AT" },
  { nombre: "Joel",                    abrev: "Jl",     osis: "JOL", capitulos: 4,   testamento: "AT" },
  { nombre: "Amós",                    abrev: "Am",     osis: "AMO", capitulos: 9,   testamento: "AT" },
  { nombre: "Abdías",                  abrev: "Abd",    osis: "OBA", capitulos: 1,   testamento: "AT" },
  { nombre: "Jonás",                   abrev: "Jon",    osis: "JON", capitulos: 4,   testamento: "AT" },
  { nombre: "Miqueas",                 abrev: "Mi",     osis: "MIC", capitulos: 7,   testamento: "AT" },
  { nombre: "Nahúm",                   abrev: "Na",     osis: "NAM", capitulos: 3,   testamento: "AT" },
  { nombre: "Habacuc",                 abrev: "Hab",    osis: "HAB", capitulos: 3,   testamento: "AT" },
  { nombre: "Sofonías",                abrev: "So",     osis: "ZEP", capitulos: 3,   testamento: "AT" },
  { nombre: "Ageo",                    abrev: "Ag",     osis: "HAG", capitulos: 2,   testamento: "AT" },
  { nombre: "Zacarías",                abrev: "Za",     osis: "ZEC", capitulos: 14,  testamento: "AT" },
  { nombre: "Malaquías",               abrev: "Ml",     osis: "MAL", capitulos: 3,   testamento: "AT" },

  // ─── Nuevo Testamento ─────────────────────────────────────────────────────
  { nombre: "Mateo",                   abrev: "Mt",     osis: "MAT", capitulos: 28,  testamento: "NT" },
  { nombre: "Marcos",                  abrev: "Mc",     osis: "MRK", capitulos: 16,  testamento: "NT" },
  { nombre: "Lucas",                   abrev: "Lc",     osis: "LUK", capitulos: 24,  testamento: "NT" },
  { nombre: "Juan",                    abrev: "Jn",     osis: "JHN", capitulos: 21,  testamento: "NT" },
  { nombre: "Hechos",                  abrev: "Hch",    osis: "ACT", capitulos: 28,  testamento: "NT" },
  { nombre: "Romanos",                 abrev: "Rom",    osis: "ROM", capitulos: 16,  testamento: "NT" },
  { nombre: "1 Corintios",             abrev: "1 Cor",  osis: "1CO", capitulos: 16,  testamento: "NT" },
  { nombre: "2 Corintios",             abrev: "2 Cor",  osis: "2CO", capitulos: 13,  testamento: "NT" },
  { nombre: "Gálatas",                 abrev: "Gal",    osis: "GAL", capitulos: 6,   testamento: "NT" },
  { nombre: "Efesios",                 abrev: "Ef",     osis: "EPH", capitulos: 6,   testamento: "NT" },
  { nombre: "Filipenses",              abrev: "Flp",    osis: "PHP", capitulos: 4,   testamento: "NT" },
  { nombre: "Colosenses",              abrev: "Col",    osis: "COL", capitulos: 4,   testamento: "NT" },
  { nombre: "1 Tesalonicenses",        abrev: "1 Tes",  osis: "1TH", capitulos: 5,   testamento: "NT" },
  { nombre: "2 Tesalonicenses",        abrev: "2 Tes",  osis: "2TH", capitulos: 3,   testamento: "NT" },
  { nombre: "1 Timoteo",               abrev: "1 Tim",  osis: "1TI", capitulos: 6,   testamento: "NT" },
  { nombre: "2 Timoteo",               abrev: "2 Tim",  osis: "2TI", capitulos: 4,   testamento: "NT" },
  { nombre: "Tito",                    abrev: "Tit",    osis: "TIT", capitulos: 3,   testamento: "NT" },
  { nombre: "Filemón",                 abrev: "Flm",    osis: "PHM", capitulos: 1,   testamento: "NT" },
  { nombre: "Hebreos",                 abrev: "Hb",     osis: "HEB", capitulos: 13,  testamento: "NT" },
  { nombre: "Santiago",                abrev: "Stg",    osis: "JAS", capitulos: 5,   testamento: "NT" },
  { nombre: "1 Pedro",                 abrev: "1 Pe",   osis: "1PE", capitulos: 5,   testamento: "NT" },
  { nombre: "2 Pedro",                 abrev: "2 Pe",   osis: "2PE", capitulos: 3,   testamento: "NT" },
  { nombre: "1 Juan",                  abrev: "1 Jn",   osis: "1JN", capitulos: 5,   testamento: "NT" },
  { nombre: "2 Juan",                  abrev: "2 Jn",   osis: "2JN", capitulos: 1,   testamento: "NT" },
  { nombre: "3 Juan",                  abrev: "3 Jn",   osis: "3JN", capitulos: 1,   testamento: "NT" },
  { nombre: "Judas",                   abrev: "Jds",    osis: "JUD", capitulos: 1,   testamento: "NT" },
  { nombre: "Apocalipsis",             abrev: "Ap",     osis: "REV", capitulos: 22,  testamento: "NT" },
];
